[package]
name = "aegis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.2"
base64 = "0.21.2"
color-eyre = "0.6"
console = "0.15.7"
dialoguer = { version = "0.10.4", features = ["fuzzy-select"] }
hex = "0.4.3"
libreauth = "0.16.0"
password-hash = "0.5.0"
scrypt = "0.11.0"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"
