[package]
name = "aegis-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.2"
hex = "0.4.3"
libreauth = "0.16.0"
password-hash = "0.5.0"
scrypt = "0.11.0"
serde = "1.0.164"
serde_json = "1.0.99"
