---
name: Continious integration

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
  push:
    branches:
      - "master"
      - "renovate/**"
    paths-ignore:
      - "**/*.md"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  ci:
    name: Test
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Just
        uses: extractions/setup-just@v2
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Get build cache
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: just build
      - name: Test
        run: just test
      - name: Lint
        run: just lint
      - name: Check formatting
        run: just format
